#file: noinspection YAMLSchemaValidation
services:
    storage:
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
        image: mongo
        container_name: storage
        ports:
            - 27017:27017
    http_tabasco:
        build:
            context: ./
            dockerfile: ./task_batcher_storage_coordinator/http/Dockerfile
        depends_on:
            storage:
                condition: service_healthy
        ports:
            - 8080:8080
    grpc_tabasco:
        build:
            context: ./
            dockerfile: ./task_batcher_storage_coordinator/grpc/Dockerfile
        depends_on:
            storage:
                condition: service_healthy
        ports:
            - 9090:9090
    broker:
        healthcheck:
            test: rabbitmq-diagnostics check_port_connectivity
        image: rabbitmq:management
        ports:
            - 5672:5672
            - 15672:15672
            - 25672:25672
    testing_processor:
        build:
            context: ./
            dockerfile: ./testing_processor/Dockerfile
        depends_on:
            broker:
                condition: service_healthy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    tabasco_test:
        environment:
            GRPC_TABASCO_HOSTNAME: "grpc_tabasco"
            HTTP_TABASCO_HOSTNAME: "http_tabasco"
        build:
            context: ./
            dockerfile: ./task_batcher_storage_coordinator/test/Dockerfile
        depends_on:
            grpc_tabasco:
                condition: service_started
            http_tabasco:
                condition: service_started
