#file: noinspection YAMLSchemaValidation
services:
    build_data_base:
        healthcheck:
            test: ["CMD-SHELL", "pg_isready", "-d", "$${POSTGRES_DB}", "-U", "$${POSTGRES_USER}"]
            interval: 5s
            timeout: 60s
            retries: 5
            start_period: 80s
        image: postgres
        container_name: build_data_base
        environment:
            POSTGRES_DB: "postgres"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "1488"
        volumes:
            - ./.github/workflows/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
        ports:
            - 5432:5432
    storage:
        image: mongo
        container_name: storage
        ports:
            - 27017:27017
    http_tabasco:
        build:
            context: ./
            dockerfile: ./task_batcher_storage_coordinator/http/Dockerfile
        depends_on:
            storage:
                condition: service_started
            build_data_base:
                condition: service_healthy
        ports:
            - 8080:8080
    grpc_tabasco:
        build:
            context: ./
            dockerfile: ./task_batcher_storage_coordinator/grpc/Dockerfile
        depends_on:
            storage:
                condition: service_started
            build_data_base:
                condition: service_healthy
        ports:
            - 9090:9090
    brocker:
        image: rabbitmq:management
    testing_processor:
        build:
            context: ./
            dockerfile: ./testing_processor/Dockerfile
        depends_on:
            brocker:
                condition: service_started
    tabasco_test:
        build:
            context: ./
            dockerfile: ./task_batcher_storage_coordinator/test/Dockerfile
        depends_on:
            grpc_tabasco:
                condition: service_started
            http_tabasco:
                condition: service_started
