name: CMake Build

on:
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: self-hosted
    container:
      image: pashandor789/dts_ci_env
    services:
      http_tabasco:
        image: distributed-testing-system_http_tabasco
        ports:
          - 9090:9090
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build project
        run: |
          mkdir build
          cd build
          cmake .. -DDTS_TEST=on
          cmake --build . -- -j $(nproc) 
      - name: Launch services
        run: |
          mkdir shared-libs
          cat .github/workflows/shared-libs.txt | xargs -I {} cp {} shared-libs
          docker-compose up --build
      - name: Tabasco test
        run: |
          cd task_batcher_storage_coordinator/test
          make test
