name: CMake Build

on:
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake .. -DTS_TEST=on
          cmake --build .
