name: CMake Build

on:
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: self-hosted
    container:
      image: pashandor789/dts_ci_env
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build project
        run: |
          mkdir build
          cd build
          cmake .. -DDTS_TEST=on
          cmake --build . -- -j $(nproc) 
      - name: Launch services
        run: |
          mkdir shared-libs
          cat .github/workflows/shared-libs.txt | xargs -I {} cp {} shared-libs
          docker-compose up --build -d
      - name: Tabasco test build
        run: |
          docker build -f ./task_batcher_storage_coordinator/test/Dockerfile -t tabasco_test .
          docker run --network=host tabasco_test
