name: CMake Build

on:
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: self-hosted
    container:
      image: pashandor789/dts_ci_env
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build project
        run: |
          ls -l
          pwd
      - name: Build project
        run: |
          mkdir build
          cd build
          cmake .. -DDTS_TEST=on
          cmake --build . -- -j $(nproc) 
      - name: Launch services
        run: |
          mkdir shared-libs
          cat .github/workflows/shared-libs.txt | xargs -I {} cp {} shared-libs
          docker-compose rm
          docker-compose build
          docker-compose up build_data_base storage
      - name: Tabasco test build
        run: |
          docker-compose run tabasco_test
      - name: Show services logs
        if: always()
        run: docker-compose logs
      - name: Stop services
        if: always()
        run: docker-compose down
