name: CMake Build

on:
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: self-hosted
    container:
      image: pashandor789/dts_ci_env
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build project
        run: |
          make build
      - name: Launch services
        run: |
          make build_launch_services
      - name: Tests run
        run: |
          make test
      - name: Show services logs
        if: always()
        run: docker-compose logs
      - name: Stop services
        if: always()
        run: docker-compose down
